### ISSUE TITLE
Not available on Package Control

### ISSUE THREAD

**Issue by jankal** [marcobiedermann/sublime-head-snippets#1]
It seems, that your plugin isn't available on Package Control.
Search: Not found https://packagecontrol.io/search/head%20snippets

**Comment by marcobiedermann** [comment]
@jankal I've already submitted this plugin to the Package Control repo. Still have to wait until [my pull request](https://github.com/wbond/package_control_channel/pull/5576) gets merged in.
In the meanwhile, you could install it manually or wait until it is available via Package Control.
Unfortunately whit takes some time.

**Comment by marcobiedermann** [comment]
@jankal I've already submitted this plugin to the Package Control repo. Still have to wait until [my pull request](https://github.com/wbond/package_control_channel/pull/5576) gets merged in.
In the meanwhile, you could install it manually or wait until it is available via Package Control.
Unfortunately whit takes some time.

**Comment by marcobiedermann** [comment]
@jankal @joshbuchea @james2doyle
My package just got published on [PackageControl](https://packagecontrol.io/packages/HTML%20Head%20Snippets)! 🎉

**Comment by joshbuchea** [comment]
Hey awesome @marcobiedermann! I'll tweet a link to it. Thanks for making that man!

**Comment by jankal** [comment]
@marcobiedermann Awesome. Just installed it ;)
